name=UNOQ_STM32_HAL
version=2.1.0
author=Sri Ranga Raj B
maintainer=Sri Ranga Raj B <sreerangaraj387@gmail.com>
sentence=STM32 HAL wrapper library for Arduino.
paragraph=Special Library specifically developed for accessing the PIN in Arduino UNO Q with the STM Pin Mappings
category=Device Control
url=https://github.com/srirangaraj-b/UNOQ_STM32_HAL
architectures=*