name=UNOQ_STM32_HAL
version=1.0.0
author=Sri Ranga Raj B
maintainer=Sri Ranga Raj B <your-email@example.com>
sentence=STM32 HAL wrapper library for Arduino.
paragraph=Provides GPIO, UART, PWM, ADC and LCD helper functions for STM32 boards.
category=Device Control
url=https://github.com/srirangaraj-b/UNOQ_STM32_HAL
architectures=stm32